WIP: More works on backend part
Domiii/dbux pull request #305
Opened 2020-09-09 08:44 UTC by edisonhello

A `BufferedFirestoreContainer` extends `FirestoreContainer` that will merge data into a big data.
A `SafetyStorage` that makes sure all VSCode share the same memento contents.

2020-09-09 10:02 UTC, edisonhello commented
#293 may be clone if this has no problem.

2020-09-09 11:59 UTC, MiccWan requested changes

2020-09-09 11:59 UTC, MiccWan commented on dbux-projects/src/backend/Backlog.js
> +import { isEqual } from 'lodash';
change to `import isEqual from 'lodash/isEqual';`?

2020-09-09 11:59 UTC, MiccWan commented on dbux-projects/src/backend/Backlog.js
>        }
The storage will be locked before the loop, no need to worry about new data been pushed while writing, thus we can make this loop O(1) (use for-of or forEach) instead.

2020-09-09 11:59 UTC, MiccWan commented on dbux-projects/src/backend/BufferedFirestoreContainer.js
> +  saveGetBuffer() {
safe?

2020-09-09 11:59 UTC, MiccWan commented on dbux-projects/src/backend/db.js
> +      Verbose && debug('writting data', data);
typo: writing

2020-09-10 09:46 UTC, Domiii commented
needs `try/finally`

2020-09-10 09:55 UTC, Domiii commented
backlog needs to identify entries by their unique key, that is a combo key of: `collectionName` and `docId`.

However, neither id nor collection name are stored inside the object to be stored; so you have to find a way to store that data in `FirestoreContaienr` when writing to the `Db` object.

2020-09-10 11:01 UTC, edisonhello commented
Also cover #307

2020-09-25 07:09 UTC, MiccWan approved these changes

2020-09-29 08:42 UTC, merged